### ISSUE TITLE
paste after black hole delete

### ISSUE THREAD

**Issue by Konfekt** [AndrewRadev/whitespaste.vim#2]
After deleting a line by "_dd, hitting p to paste has no effect, but has to be hit twice.

This affects whitespaste as well as pasta.vim

**Comment by AndrewRadev** [comment]
There's not much more I can do about this issue, I think. I wish I'd pasted a link to the mailing list thread, but either way, I'm pretty sure I got no response :/.

I'm going to close this issue for the moment.
